### ISSUE TITLE
Demo - Adding Shipping Address Causes Crash

### ISSUE THREAD

**Issue by decidedlygray** [markjackmilian/Xam.PayPal.iOS#2]
Hello there,

I am trying to add a shipping address to the demo app just to see if it works, but it is crashing. I was wondering if you might be able to help me figure out what I'm doing wrong?

In my `ViewDidLoad` within `Xam.PayPal.iOS.Demo/ViewController.cs`, I changed the appropriate line to allow for a provided address, instead of `.PayPal` I now have `.Provided`:
```
...
_payPalConfig.PayPalShippingAddressOption = PayPalShippingAddressOption.Provided;
...
```

Next, within `Xam.PayPal.iOS.Demo/ViewController.cs`, I've changed the `PayNowTouched` method to include a `PayPalShippingAddress`:
```
partial void PayNowTouched(Foundation.NSObject sender)
{
    var payment = PayPalPayment.PaymentWithAmount(new Foundation.NSDecimalNumber(24.12), "EUR", "Mark Jack Milian", PayPalPaymentIntent.Sale);

    var address = new PayPalShippingAddress(){
        RecipientName = "DG Test" ,
        Line1 = "1600 Pennsylvania Ave NW",
        Line2 = "",
        City = "Washington",
        State = "DC",
        PostalCode = "20500"//,
        //CountryCode = "USA",
    };
    
    payment.ShippingAddress = address;

    var paymentViewController = new PayPalPaymentViewController(payment, _payPalConfig, this._myDelegate);
    this.PresentViewController(paymentViewController, true, null);
}
```

The following exception gets thrown when the new `PayPalPaymentViewController` is created (second to last line of `PayNowTouched`):
```
Unhandled Exception:

System.Exception: Could not initialize an instance of the type 'Xam.PayPal.iOS.PayPalPaymentViewController': the native 'initWithPayment:configuration:delegate:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false. occurred
```

Any help would be greatly appreciated. Do I need to make changes to `Xam.PayPal.iOS\ApiDefinition.cs`?

Thanks!

**Comment by markjackmilian** [comment]
Hi! I’ll check asap!
Thanks for your feedback

Inviato da iPhone

Il giorno 01 apr 2018, alle ore 01:17, Decidedly Gray <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hello there,

I am trying to add a shipping address to the demo app just to see if it works, but it is crashing. I was wondering if you might be able to help me figure out what I'm doing wrong?

In my ViewDidLoad within Xam.PayPal.iOS.Demo/ViewController.cs, I changed the appropriate line to allow for a provided address, instead of .PayPal I now have .Provided:

...
_payPalConfig.PayPalShippingAddressOption = PayPalShippingAddressOption.Provided;
...


Next, within Xam.PayPal.iOS.Demo/ViewController.cs, I've changed the PayNowTouched method to include a PayPalShippingAddress:

partial void PayNowTouched(Foundation.NSObject sender)
{
    var payment = PayPalPayment.PaymentWithAmount(new Foundation.NSDecimalNumber(24.12), "EUR", "Mark Jack Milian", PayPalPaymentIntent.Sale);

    var address = new PayPalShippingAddress(){
        RecipientName = "DG Test" ,
        Line1 = "1600 Pennsylvania Ave NW",
        Line2 = "",
        City = "Washington",
        State = "DC",
        PostalCode = "20500"//,
        //CountryCode = "USA",
    };

    payment.ShippingAddress = address;

    var paymentViewController = new PayPalPaymentViewController(payment, _payPalConfig, this._myDelegate);
    this.PresentViewController(paymentViewController, true, null);
}


The following exception gets thrown when the new PayPalPaymentViewController is created (second to last line of PayNowTouched):

Unhandled Exception:

System.Exception: Could not initialize an instance of the type 'Xam.PayPal.iOS.PayPalPaymentViewController': the native 'initWithPayment:configuration:delegate:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false. occurred


Any help would be greatly appreciated. Do I need to make changes to Xam.PayPal.iOS\ApiDefinition.cs?

Thanks!

**Comment by markjackmilian** [comment]
Hi,
you must set Country Code correctly.
CountryCode = "USA"  => CountryCode = "US"
See [https://developer.paypal.com/docs/integration/direct/rest/country-codes/]

Pls try again.

**Comment by markjackmilian** [comment]
Can i close this issue? It's working?

**Comment by decidedlygray** [comment]
Hey, sorry for the late follow up. Using “US” did not work either
